kind = "api"
previewPath = "/api"
title = "Discord 地震速報Bot"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "Discord Bot"

[services.development]
run = "python bot/earthquake_bot.py"

[services.production]

[services.production.run]
args = ["python", "bot/server.py"]

[services.production.run.env]
PORT = "8080"

[services.production.health.startup]
path = "/healthz"
